version: '3.8'

services:
  laravel:
    image: php:8.1-fpm
    container_name: laravel_app
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8000:8000"
    environment:
      DB_HOST: laravel_db
      DB_PORT: 3306
      DB_DATABASE: visetechsystem
      DB_USERNAME: root
      DB_PASSWORD:
    depends_on:
      - db

  vue:
    image: node:18
    container_name: vue_app
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    command: npm run dev
    environment:
      - VITE_API_BASE_URL=http://localhost:8000/api

  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: visetechsystem
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"

networks:
  default:
    driver: bridge