import './bootstrap.js';
import { createApp } from 'vue';
import App from './App.vue';
import router from './router';
import store from './store/index.js';
import VueSweetalert2 from 'vue-sweetalert2';
import 'sweetalert2/dist/sweetalert2.min.css';
import VueTelInput from 'vue-tel-input';
import 'vue-tel-input/vue-tel-input.css';
const app = createApp(App);
app.use(router);
app.use(store);
app.use(VueSweetalert2);
app.use(VueTelInput);
app.mount('#app');
